---
author:
  - 'Mike Eldridge <diz@cpan.org>'
build_requires:
  Class::Accessor::Fast: 0
  Directory::Scratch: 0
  FindBin: 0
  POE::API::Peek: 0
  Template: 0
  Test::MockObject: 0
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hopkins
no_index:
  directory:
    - inc
    - t
requires:
  Cache::FileCache: 0
  Catalyst::Engine::Embeddable: 0.000002
  DBIx::Class: 0.08103
  DateTime: 0.37
  DateTime::Event::MultiCron: 0.01
  DateTime::Set: 0.25
  File::Monitor: 0.10
  Getopt::Attribute: 1.44
  List::Object: 0.01
  Log::Log4perl: 1.12
  POE: 1.005
  POE::API::Peek: 1.34
  POE::Component::JobQueue: 0.55
  POE::Component::Server::HTTP: 0.09
  POE::Component::Server::SOAP: 1.11
  POE::Wheel::Run: 1.2179
  String::Escape: 2002.001
  Sys::Hostname::FQDN: 0.10
  Tie::IxHash: 1.21
  XML::Simple: 2.18
resources:
  license: http://dev.perl.org/licenses/
version: 0.900
