#!/usr/bin/perl

use DBI;
use Data::Dumper;

my $dbh = DBI->connect("dbi:SQLite:dbname=hopkins.db","","");

my $sth = $dbh->prepare('SELECT COUNT(*) FROM tasks WHERE name = ?');

$sth->execute('Fart');

print Dumper $sth->fetchrow_hashref;

exit;

